title: Ann's blog
author: Ann
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is just for learning GitHub.

# social links
twitter_username: amcgrath815
github_username:  amcgrath815

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
